{% set version = "2.1" %}

package:
  name: jbig
  version: {{ version }}

source:
  - url: https://www.cl.cam.ac.uk/~mgk25/jbigkit/download/jbigkit-{{ version }}.tar.gz
    sha256: de7106b6bfaf495d6865c7dd7ac6ca1381bd12e0d81405ea81e7f2167263d932
  - path: CMakeLists.txt

build:
  number: 2002
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}

test:
  commands:
    - test -f $PREFIX/lib/libjbig.a  # [not win]
    - if not exist %LIBRARY_PREFIX%\\bin\\jbig.dll exit 1  # [win]

about:
  home: https://www.cl.cam.ac.uk/~mgk25/jbigkit
  license: GPL-2.0
  license_family: GPL
  license_file: COPYING
  summary: 'Implementation of the JBIG1 data compression standard'

  description: |
    JBIG-KIT provides a portable library of compression and decompression
    functions with a documented interface that you can include very easily
    into your image or document processing software.
  doc_url: https://www.cl.cam.ac.uk/~mgk25/jbigkit/
  dev_url: https://www.cl.cam.ac.uk/~mgk25/git/jbigkit/

extra:
  recipe-maintainers:
    - nehaljwani
    - mingwandroid
    - ocefpaf
    - seanyen
