# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Mzn+XnvgEjoduBnrG227rZtZc4zRDXYoEdyGXldluU7VWWt6nnXs1V57jp6TJt7lhBGwuFcsk61vhqMThXUgeHPey2CehGokgp+1/aqKwiFgNHEq3hYN5MjcIyci5R7ktXHoa0Rac+bp5zM0nBRFqM5M/GynueNR62HeSUlOQ7Wv6xmtLe922LJ9IsoP/nELBBxxGaWcIyRI60RSX7AjUhC64dXiIvbt9GKPyQ8Ff9xZHx4kMVdL3datzOdYn1OdM22INz/AYzm9xOIEre5QJfRZXGQe931KSbsgXYKqDyBCKHKnTHlad7yAPUTk4avuhcYOCyFm9VHTguXZP89a2qySiXNO+atEsFj4jioabqZ/1n6phltlsz18+2K+ET+jlZgsZY2Rm7esK/X5JISvEXT712AEiJJhs7AbcgOxX9x424G7mRHueTUVp9PzA4PvHj8qxcOrbjSqvU61U7roP5HQamnVneUBbpG7DFwsjhNFPtY7bPqXBeGa/b/XaIqmId6TzmePFAmATjrApfC6FfY7o5s3zBZME76oGHZmbNX74uUosMr6t2gNAM8sls5QpgtnG+3K321AYdbr68kkIsm82/NFuNsP96FO717cnCWkMeB++TWoTyggEBRrNcxZO2q6tGPIQI00sVA0HjREoByMTOb2eUc9AApbln8lkQo="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
