appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: P2P4x8uOWTOKMis+p7Ri0sDy0VD05Qg6IJAc5Y9wfwTlg9o+1y2+LLwpVDnVlrzhLnOn3BExuEKLdgjBOkeaQHlbKplsK+ohRX0IPS6To5036EyYbKMw+jQP6q2q4adJT3DawWOHExsleNDcPevST/XvRZRQmmQpn8XE2nPBa7FqaaRnby9ezR2K43jkByWPNlTwuhEshUN4P6EHZ2WKy68dHeGqn4B6mU3oHT2y4mX8U9uekN1fKcH5fHQ+iBQzS3MwBzBqwt3urO0zEGcu31rV0dNUjRzYKMrzu4AlBOd2BE4C74FT7fcqQPy9/GxpFQ/u5zqYVV9yzuudcDucpJTF+OFAb33HFp8lT6a6ENztLkekAFc6ykMKZPlhTmjKkUjWV50kPfthbVJSqBuTGfhI03Oj3E5LOBaGOoSF83GxGIToTaer72MKhkdSw6IM1zSzt6L9Te1HsZime65WmvdYepwEbKsO/kwAz42HhuDaQzOPkxjhemt2VUSaaIRyaOfRQDxS41iTJK1GRsP16crr4dFASSa+V88HUKrg3+BPdIS3EwHs4alda5b6xEUUYWczAC6QKZMOSzwPV4Pppvv6LYDzq9lTbWb7VFOVX6uPfCa2vMsHsyf9UVJgrsUPmtzd/BX+frJS6blUxPrEnHE1Zz0dXbI0V1pIvYPavHc=}
conda_forge_output_validation: true
